securingsincity/react-ace

src/ace.jsx
Hi, thanks for the component!
I have an issue: if i do this:
```javascript
var editor = React.render(React.createElement(AceEditor, {
value: source,
onChange: createAction,
}), document.body);
function createAction(newSource) {
source = newSource;
if (editor) editor.setProps({value: source});
}
```
i get an infinite loop because after the component.setProps({value}) the ace.setValue(value) will be called and this triggers the "change" event even though the ace.getValue() already equal to the new value.
This pull request fixes that by checking the ace.getValue() before refreshing the ace editor.
=> fix infinite loop when feeding the onChange(value) back to setProps({value})

example/example.jsx, src/ace.jsx
In order to use parts of the Ace editor API that aren't yet supported, it would be great to have access to `this.editor` outside of the React element.
One easy way of doing this is to pass editor into the onLoad function:
```javascript
if (this.props.onLoad) {
this.props.onLoad(this.editor);
}
```
Examples of Ace features I need to use are:
```javascript
session = editor.getSession();
session.setTabSize(2);
session.setUseSoftTabs(true);
session.setUseWrapMode(true);
// ...
editor.scrollToRow(0);
editor.selection.clearSelection();
editor.focus();
```
=> Give access to Ace editor object in onLoad.

src/ace.jsx
This resolves an issue where text is highlighted whenever the `value` prop is changed.
=> set cursor to end of editor text

package.json
modules which don't use in the source should be placed in `devDependencies` field
=> move modules to devDependencies

src/ace.jsx
better to use enumerable own properties
see as reference: http://stackoverflow.com/questions/22658488/object-getownpropertynames-vs-object-keys
=> replace Object.getOwnPropertyNames with Object.keys 

src/ace.jsx
In some flux architecture, if it listens to `change` event before initialize, it's easy to cause a Infinite loop.
(Change) => (Set Value) => (Change) => (Set Value) => ....
So, listen to change event after initialize will much better.
=> move onChange to tail to avoid Infinite loop

src/ace.jsx
In meteor, it is often required to change the paths from where the modules, themes and others are loaded. For this, we need access to the “ace” object:
Example:
```
onLoad(ace: AceAjax.Ace, editor: AceAjax.Editor) {
var acePath = "/ace";
ace.config.set("modePath", acePath);
ace.config.set("themePath", acePath);
ace.config.set("workerPath", acePath);
}
```
Having this callback would be really helpful!
=> Add the possibility to modify ace behaviour before load.

package.json
The current peer dependencies does not include support for React 0.14.0.rc1.
This approach seems like to allow using the current react-ace version with react 0.14.0.rc1.
I think another approach could be `"react": ">=0.11.2"`.
=> Add support to react 0.14.0.rc

src/ace.jsx
The onChange handler was being applied twice, once before the initial editor.setValue() method was called. Besides removing the duplicated code, this helps because an automatic change event was fired whenever an initial value was set. 
I feel this is a better setup because if the user wants an initial change event, they can just fire one manually.
=> Allow devs to set an initial value without triggering a change event

src/ace.jsx
#38 && #10  target on the same problem. But this problem still exist.
In native input && textarea component, the onChange callback will not be called when the value props change.
But in AceEditor, onChange will be called.
see https://jsfiddle.net/crysislinux/402othpj/1/
This behavior will cause problem in some Flux implementation (e.g Alt)
Alt separate each dispatching, a second dispatching cannot be triggered if the first one has not finished. 
But now,
value changed --> dispatch --> value prop changed --> setValue called --> change event triggered --> onChange called --> trigger alt action to save value in alt store --> another dispatch --> boom
In short, the setValue call should not lead a onChange call.
=> Fix setValue onChange infinite loop

README.md, src/ace.jsx
This adds the ability to specify a keyboardHandler on the React component (such as vim or emacs).
`setKeyboardHandler` will only execute if the prop is set - this is because we cannot hardcode the default value as it is platform specific (osx/windows/etc).
=> Add prop for keyboardHandler

src/ace.jsx
I think finally we should have a random id for component lifecycle, and avoid let people assign name. If you have two editors have same `name` props, it won't works.
=> remove call ace.edit on every time receive props

package.json
brace has several updates in it, including bringing ace to version 1.2.2.  This just updates the package.json reference to brace to the latest version.
=> update brace to 0.7.0

src/ace.jsx
wrap mode was only being set when the component mounts, not when props were received ie not possible to change the mode
=> update wrapMode if wrapEnabled prop changes

README.md, src/ace.jsx
This adds the `enableBasicAutocompletion` and `enableLiveAutocompletion` editor options. It also removes some duplication on the assignment of the editor options.
=> add `enableBasicAutocompletion` and `enableLiveAutocompletion`

src/ace.jsx
The `editor` leaks event listeners if you just `null` it: https://github.com/ajaxorg/ace/issues/2085. Calling `destroy()` triggers the full cleanup, so let's do that.
=> componentWillUnmount: destroy editor

example/index.js, src/ace.jsx
This removes the need to give each instance of react-ace a unique id
while also eliminates issues with not finding the ace div element in
certain use cases such as inside iframes.
=> Initialize ace editor with a dom node reference instead of an element id

example/index.js, src/ace.jsx
Reverts securingsincity/react-ace#93
=> Revert "Initialize ace editor with a dom node reference instead of an element id"

src/ace.jsx
I am experiencing an issue where ``componentWillReceiveProps`` is called before ``componentDidMount``, because of this ``this.editor`` is undefined and the call to ``getValue`` results in a ``TypeError``. According to the React documentation on the lifecycle of components ``componentWillReceiveProps`` is not called on the initial render, thus I do not understand why this issue appears (see #106). This PR is a simple fix to avoid the explained issue, however I am uncertain whether the issue occurs because of some wrong initialization on my end, is anyone else also experiencing this issue? The issue only happens when the component has already been mounted before and is now remounted (i.e. you navigated away from the page and revisit it using react-router).
Edit:
I have investigated the …
=> Check if this.editor is defined inside componentWillReceiveProps

src/ace.jsx
There is an error in the last version of 'react-ace': it is impossible
to change classes applied to ace-editor instance.
For now `className` applied as a prop of `div` to which Ace Editor will
be mounted, so, mounted Ace Editor appends internal class names (like
`ace_editor` and theme classes, for example) to class names that have
been passed by `className` prop. And when `react-ace` component receives
other value of `className` prop from its parent, this value overrides
internal classes applied during Ace Editor initialization, and the
component starts to working improperly.
This pull request changes this behavior and applies class names from
`className` prop directly to Ace Editor instance.
=> Apply className prop directly to editor instance

src/ace.jsx
fixes #120, and other redux related issues,
problem: everytime `dispatch` is called in `onChage` that triggers react-ace's `componentWillReceiveProps` which in turn calls `setValue` on underlying editor, which causes it to loose cursor position
this pull request fixes it
=> Preserve cursor position on `setValue`

README.md, src/ace.jsx
This adds two new props to set markers and annotations, which both use plain objects and are mapped to what Ace needs (i.e. `Range`s for markers).
Small demonstration (the icon in the gutter also has a tooltip):
```jsx
<ReactAce
uniqueId="editor"
value="(test "
markers={[{
className: 'error-marker',
startRow: 0,
startCol: 6,
endRow: 0,
endCol: 7
}]}
annotations={[{
column: 6,
row: 0,
text: 'Some wild demo error.',
type: 'error'
}]}
editorProps={{ $useWorker: false }}
/>
```
The worker needs to be disabled so that Ace doesn't try to add other markers/annotations by checking the syntax itself.
=> Add markers and annotations

src/ace.jsx
This is done by making sure `editor` has the property in the `$options` dictionary. If not the property is silenced.
Fixes #95 
Fixes #111
=> Avoid passing unknown options to Ace

package.json
This is a friendly FYI that, while its presence is harmless, you should be able to dispense with this dep; `babel@6` is just a vestige that doesn't really do anything.
=> Delete babel dep

example/.babelrc, example/package.json, package.json, src/ace.jsx
AceEditor currently has to be wrapped in order to be aligned as it does not accept style overrides.
```
<div style={{ position: 'absolute', display: 'flex', height: '100%', width: '100%' }}>
<Canvas style={{ flexGrow: 3 }}>
...
</Canvas>
<div style={{ flexGrow: 2 }}>
<AceEditor
mode="javascript"
theme="monokai"
editorProps={{$blockScrolling: true}}
height="100%"
width="100%"
value={code}
/>
</div>
</div>
```
With this PR 
```
<AceEditor
style={{ flexGrow: 3 }}
...
```
=> Allow users to override styles

src/ace.jsx
This lets us dynamically create disconnected DOM elements with ace functionality, that get inserted into the document at a later time. 
The specific use case I have is creating an `AceBlock` node type to be inserted into a ProseMirror instance (http://prosemirror.net/)
=> render by reference to enable delayed dom injection

src/ace.jsx
instead of manually implementing shouldComponentUpdate, I'm using the recommended approach of extending `React.PureComponent` that class implements shouldComponentUpdate with a shallow compare, which seems to be good enough for react-ace
=> fixes #115 skip updates using PureComponent

README.md
[PR137](https://github.com/securingsincity/react-ace/pull/137) can override styles like this
```js
<AceEditor
style={{ flexGrow: 3 }}
...
```
So I add `style` to available props
=> add `style` to available props

package.json, src/ace.jsx
In 15.5, instead of accessing PropTypes from the main React object,
install the prop-types package and import them from there.
https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes
=> Use prop-type package instead of React.PropType

types.d.ts
Without this change this produces the following error:
(123,13): error TS2605: JSX element type 'AceEditor' is not a constructor function for JSX elements.
Types of property 'state' are incompatible.
Type 'undefined' is not assignable to type 'Readonly<{}>'.
=> React.Component cannot accept undefined for props or state

types.d.ts
Minor fix for typescript type definitions
The 'editorProps' property '$blockScrolling' can take number as well as boolean. Type definition set as union of number and boolean to reflect that.
[README.md](https://github.com/securingsincity/react-ace/blob/master/README.md) example shows $blockScrolling property as a boolean
```javascript
// ...
render(
<AceEditor
mode="java"
theme="github"
onChange={onChange}
name="UNIQUE_ID_OF_DIV"
editorProps={{$blockScrolling: true}}
/>,
document.getElementById('example')
);
```
#211 Typescript Supprt
=> Fix Typescript type definition for 'EditorProps'

src/ace.js
`resize` should be called on `componentDidMount` after the component got initial value for the `height`. Also it should be called every time on `componentDidUpdate` after the editor received the new value for the `height`.
=> Fix sizing issues

package.json
npm 4 is splitting the prepublish script into two new: prepare and prepublishOnly.  
* prepare will have the same behavior that prepublish has now. Commands in this script will run both before publishing and on npm install.
* prepublishOnly, as seen from its name, will run only before publishing the package.  
Also, prepublish will receive a warning about the changes.
prepublish ->prepublishOnly
=> chore(package.json): use prepublishOnly

package.json, tests/src/ace.spec.js, tests/src/split.spec.js
- remove `react` and `react-dom` from `dependencies` and move them to `devDependencies`
- update `peerDependencies` to allow use React 16
- update react to 16
- replace `enzyme-adapter-react-15` with `enzyme-adapter-react-16`
- remove `react-addons-test-utils`, we don't need it with `enzyme-adapter-react-16`
Replaces #268
Replaces #269
Fixes #279
=> chore(package): update to react 16

docs/FAQ.md, src/ace.js, src/split.js, tests/src/ace.spec.js, tests/src/split.spec.js
In ace, it is possible to remap a keybinding by using the bindkey method,
it should be possible with react-ace too.
This can now be done by specifying an existing method name for `exec` instead of a function.
- Implemented the change in both src/ace.js and src/split.js
- Added unit tests for both ace.js and split.js. 
I should mention here that ace seem to use a MultiHashHandler by default, 
and thus the new key-bindings are appended to the existing ones, but the most recently
added has the priority.
- Updated the FAQ.md next to the "How do I add key-bindings?" paragraph
I did not edit the example (even if I tested on it), because the `commands`
props was not used, and so I didn't want to complexify it.
https://github.com/securingsincity/react-ace/issues/285#issuecomment-334810082
=> #285: added the possibility to change key bindings of existing commands.

docs/Ace.md, docs/Split.md, example/index.js, example/split.js, src/ace.js, src/editorOptions.js, src/split.js, tests/src/ace.spec.js, tests/src/split.spec.js
Added changeCursor event. 
I wanted to detect that the position of the cursor was changed.
Ace emitted a changeCursor event, but react-ace did not have a handler to receive it, I added it. 😄
=> Add support onCursorChange event

src/ace.js, tests/src/ace.spec.js
Add a props name `debounceChangePeriod`. If this props is specified, a `debounce` is set on `onChange` event with the specified value in milliseconds.
* props `debounceChangePeriod` of type `PropTypes.number`
* debounce function
* debounce of the `onChange` method if the props is specified
Just FYI I've used it in [this tool](https://bertrandmartel.github.io/callflow-workshop/) I made. [Here](https://github.com/bertrandmartel/callflow-workshop/blob/master/src/component/SessionContainer.js#L492) is where the props is set in AceEditor
=> add debounce props for onChange event

docs/Modes.md
Added links on doc for brace, brace/mode, brace/theme & brace/keybinding, under the topic _'How to add modes, themes and keyboard handlers'_
https://github.com/thlorenz/brace
https://github.com/thlorenz/brace/tree/master/mode
https://github.com/thlorenz/brace/tree/master/theme
https://github.com/thlorenz/brace/tree/master/keybinding
=> Add links to 'brace' to improve doc

docs/Ace.md
Just a doc update as it was not clear that the CSS class for markers needed to have `position: absolute`
=> Clarified markers doc and fixed link

package-lock.json, package.json
HMR crashes with the following error 
After a little debugging turns out `hash` property is added in webpack-dev-server@3.1.3 where React-ace currently uses 3.1.2. 
This PR resolves this version issue
=> webpack-dev-server updated to latest version

src/ace.js, tests/src/ace.spec.js
See #300 / https://github.com/securingsincity/react-ace/issues/300#issuecomment-401008555
Changing updates processing order when receiving props.
The issue was annotations that sometimes could not be set.
It seems related to the session management in ace. I think when the text is changed, a new session is created and the annotation change event somehow misses its session.
=> On receiving props, process editor value update in priority

types.d.ts
The Typescript interface for AceOptions was missing debounceChangePeriod option
I added debounceChangePeriod to the the interface
TypeScript complains if you try to use that prop
=> AceOptions interface missing debounceChangePeriod

src/ace.js, src/diff.js, src/split.js, tests/src/ace.spec.js, tests/src/split.spec.js
Starting with React 16.3, several lifecycle functions are aliased to versions prefixed with `UNSAFE_` indicating that their usage is discouraged. In future versions they will be deprecated and removed[1]. One of them, `componentWillReceiveProps`, is heavily used in `react-ace`. To act proactively, this PR is removing the usage of this lifecycle function.
Additionally, some test failures due to changes in the shallow wrapper were addressed.
Usages of `componentWillReceiveProps` in `AceEditor` & `SplitEditor` components are moved to the `componentDidUpdate` function.
[1]: https://reactjs.org/blog/2018/03/27/update-on-async-rendering.html
=> Adding compatibility for React >= 17

example/diff.js, example/index.js, example/split.js, package-lock.json, package.json, src/ace.js, src/diff.js, src/split.js, tests/setup.js, tests/src/ace.spec.js, tests/src/split.spec.js, webpack.config.example.js
Currently, `react-ace` is using `brace` for bundling the underlying ace editor's files. `brace` unfortunately is several versions behind the official release. Therefore this PR is moving from `brace` to the official `ace-builds` distribution.
* Replacing `brace` package with `ace-builds` and adapting imports accordingly
* Adapting tests to newly added css classes
Fixes #512.
=> Replacing `brace` with `ace-builds`.

src/ace.js
Move `editor.focus` after `editor.resize` in `componentDidMount`
Move `editor.focus` after `editor.resize` in `componentDidMount`.
The editor has a significant/visible delay in showing the content in some, but not all cases. The editor shows up empty first and then expands. In my case the editor has a border, which makes it look worse. Before it expands, it just shows a thick black line.
This change fixes that. I have yet to reduce my case to a minimal demo but I'll probably do that in the next few days.  This problem may have something to do with the order of position calculating & style changes in the implementation of `editor.resize` and `editor.focus`.
And it does make some sense to focus the editor **after** it's resized. Currently in `componentDidUpdate`, `editor.focus` is replaced …
=> WIP: focus editor after resize in componentDidMount

package.json
`husky` and `pretty-quick` should be installed as development dependencies but not as production dependencies.
=> Move `husky` and `pretty-quick` to devDependencies

types.d.ts
Inclusion of `onCursorChange` to types
Typescript error when using `onCursorChange` on local project.
=> Included onCursorChange to types.

src/ace.js, tests/src/ace.spec.js
Changes the logic in `handleMarkers` to exclude the special markers for active line and selected word.
* Added check that current marker does not have special class name `ace_active-line` or `ace_selected-word` before clearing it.
* Added new test to verify new behaviour.
* Changed test "should clear the markers" to reflect that not all markers should be cleared anymore.
Fixes #190.
=> Do not clear active line and active word markers

src/ace.js
Add option to disable navigating to end of file on mount
* Added a boolean `navigateToFileEnd` property on the `AceEditor` component
* Users might not want the default behaviour (I certainly don't want it) - will be good to have that configurable
=> Added optional prop to disable navigating to end of file

src/ace.tsx
Correctly marks the `style` prop as optional since it has a default prop defined. Also updates it's type to be of `React.CSSProperties` since that's what it's getting used as once it's passed into the root `div`.
- Add optional operator to the `style` prop.
- This prop has a default prop so it should not be marked as required in the props interface.
- Convert the type of `style` from `any` to `React.CSSProperties`
- This is the type which is expected in the `style` prop of all react elements.
=> Mark `style` prop as optional and modify the type to more accurate for React Components.

src/split.tsx
This PR provides a fix for the split editor not having the properly-specified theme.
The general editor around the split, subeditors did not have a set theme, so it would use the default.  As a result, this caused its subeditors to follow the same theme, overwriting whatever theme was set for the split editors.  This includes a line to set the parent editor to the same theme.
I've tested this to make sure it works as expected.
=> Fix theme not set properly for split editor

docs/Ace.md
I updated the example code to include autocompletion and snippets, as many people likely would use this feature. It wasn't apparent to me that you needed to import "ace-builds/src-noconflict/ext-language_tools" to get autocomplete and snippets to work.
=> Updated Ace.md

src/editorOptions.ts
`react-ace` is almost SSR ready. The main render function merely inserts an empty div, which is then populated by ace in `componentDidMount`. Because `componentDidMount` is not fired during SSR, SSR should result in an empty div. Ideally we would start with the content that would be present after the initial call to `editor.resize()`, but an empty div is better than failing.
Currently `react-ace` fails during SSR because `require("ace-builds")` fails. ace-builds expects window to exist, but only to attach a global ace object to. react-ace doesn't actually use that global ace instance, rather it uses the handle to ace returned by require. And, again,
because all of the work is done in `componentDidMount`, just not failing during SSR doesn't require mocking up much of any kind of realistic …
=> Enable Simple SSR

package.json, src/types.ts
The current prettier configuration is not consistent with the formatting
used throughout the project. As a result, running the formatter on a
fresh repository results in a large number of spurious formatting
changes. This commit adjust the formatting rules to the point where
running the formatter only results in a single small change to
src/types.ts, which is also included in the commit.
In addition, because the formatting options are passed on the command
line through npm run, this prevents tools like VSCode from understanding
the project formatting guidelines. Moving the prettier configuration
into package.json enables integration with third-party tools.
Changes to package.json to move the prettier configuration from command line options to part of package.json itself, as well as …
=> Fix prettier configuration.

src/types.ts
This callback always has editor passed as first argument and optionally has args passes as second argument as can be seen in https://github.com/ajaxorg/ace/blob/master/lib/ace/commands/default_commands.js.
=> fix typescript binding for ICommand.exec()

package.json
A prepare script will ensure that the devDependencies are installed and the build command is run after an install from GitHub.
=> Add prepare script to enable GitHub install.

package.json
Add arrowParens: avoid to the prettier configuration to avoid reformatting files on initial clone. This will help keep PRs compact.
=> Fix prettier configuration (again).

src/ace.tsx, src/split.tsx
When I add `AceEditor` in shadow dom, there is no `ace_editor.css` in `#shadow-root`, which makes `AceEditor` looks messy.
=> fix no ace_editor.css in shadow dom

src/ace.tsx
Allow editor to be reset to empty value by passing an empty value.
Removed check if next props are empty before setting the new value.
https://github.com/securingsincity/react-ace/issues/894
Closes #894
=> Allow Editor to be reset to empty value by passing an empty value.

README.md
GitHub Pages supports HTTPS.
You can also enforce HTTPS for this repo's GitHub Pages site.
For more details, please refer to the link below.
https://docs.github.com/en/github/working-with-github-pages/securing-your-github-pages-site-with-https
=> Use https for demo sites

src/ace.tsx, src/split.tsx, src/types.ts
Fix type for exec param in ICommand interface
Type for ICommand exec param can be also a string according to FAQ example https://github.com/securingsincity/react-ace/blob/master/docs/FAQ.md#how-do-i-change-key-bindings-for-an-existing-command and  type checking in source code https://github.com/securingsincity/react-ace/blob/master/src/ace.tsx#L291
=> Fix type for exec param in ICommand interface

src/ace.tsx
Import Range from `ace-builds` in ace.tsx instead of relying on `EditorOptions.getAceInstance`.
Attempting to use `react-ace` to import `Range` when `window.ace` is defined results in the Range package not being found.
I don't see any reason why not to import Range directly from `ace-builds`, since that's already the approach taken in `split.tsx`
Related issue that this PR is intended to address: https://github.com/securingsincity/react-ace/issues/954
=> Import Range from ace-builds in ace.tsx to match split.tsx

src/ace.tsx, tests/src/ace.spec.js
Accept mode as object or string
React-ace forces me to use a syntax mode defined in this namespace: "ace/mode/?" whereas Ace setMode can accept both strings and objects. It allows us to inject a custom Ace.SyntaxMode for example or use another defined in another namespace with:
```javascript
{ path: "path/to/mode" }
```
[Ace repo](https://github.com/ajaxorg/ace#ace-ajaxorg-cloud9-editor):
```javascript
var JavaScriptMode = ace.require("ace/mode/javascript").Mode;
editor.session.setMode(new JavaScriptMode());
```
=> Accept an object as mode

src/ace.tsx
Prevent the following error if theme property is empty or undefined
> index.js:1 Unable to infer path to ace from script src, use ace.config.set('basePath', 'path') to enable dynamic loading of modes and themes or with webpack use ace/webpack-resolver
test if theme property exists and is not empty before set editor option
=> Prevent no theme error

src/ace.tsx, tests/src/ace.spec.js
- Fix `componentDidUpdate` to re-set the `this.editor.getSession().setAnnotations` if the `value` changes because changing value creates a new `session` which means the previous `annotations` are no longer rendered
- Added test for persisting annotations when updating `value` prop
=> Fix changing value loses annotations

src/ace.tsx
fix Uncaught TypeError: Cannot read properties of undefined (reading 'destroy')
Fix this problem.
> Uncaught TypeError: Cannot read properties of undefined (reading 'destroy')
add guard  when componentWillUnmount trigger.
=> Fix Uncaught TypeError: (reading 'destroy')

src/types.ts, types.d.ts
Quick fix for `foldStyle` option in `IAceOptions`
Note: I checked to make sure there isnt some additional logic before this option is passed to `ace.editor.setOptions` that would justify it taking a `boolean` instead of what `setOptions` accepts for `foldStyle`  ( one of the following: `"markbegin" | "markbeginend" | "manual"` ).
Changes: 
- `foldStyle? boolean`  -> `foldStyle? "markbegin"|"markbeginend"|"manual"` in [react-ace/types.d.ts](https://github.com/bouzidanas/react-ace/blob/fix-foldstyle-option/types.d.ts)
-   `foldStyle? boolean;`  -> `foldStyle? "markbegin" | "markbeginend" | "manual";` in [react-ace/src/types.ts](https://github.com/bouzidanas/react-ace/blob/fix-foldstyle-option/types.d.ts)
Documentation:
- No need to change documentation
References:
- [Ace Documentation on …
=> Fix foldstyle option

src/types.ts
`newLineMode`  is not a boolean, update it according to https://github.com/ajaxorg/ace/wiki/Configuring-Ace#session-options
=> fix type annotation of newLineMode

src/types.ts
ace-builds defines scroller as an HTMLElement. This change avoids type errors when using IAceEditor as the type of the editor reference returned from onLoad.
A small change to the `react-ace` typings.
To match `ace-builds`, specifically the `scroller` element defined here: https://github.com/ajaxorg/ace-builds/blob/master/ace.d.ts#L683.
=> Update types.ts to match ace-builds

src/ace.tsx
I ran into a bug where the `onChange` handler is attempted to be called on the unmounted element (because of the debounced `onChange` method). Thus, it throws `Cannot read properties of null (reading 'getValue')`.
=> `this.editor` null check

src/types.ts
It adds the `readOnly?: boolean;` property to the `ICommand` interface.
The only thing missing was the type. I checked and the commands work correctly.
=> Add readOnly property to ICommand interface

src/types.ts, types.d.ts
The `showInvisibles` type has been expanded to allow for a `string` value.
The type for `showInvisibles` can now also be a string as it's possible to only include a subset of invisibles you wish to show (for example: `showInvisibles: 'space,tab'`).
https://github.com/ajaxorg/ace/pull/4226
=> Bugfix: `showInvisibles` type

example/index.js, package-lock.json, package.json, src/ace.tsx
use new ace-builds version
added the "enableMobileMenu" option
use new ace-builds version
added the "enableMobileMenu" option
https://github.com/ajaxorg/ace/pull/5580
=> bump ace-builds up to 1.36.3 and added their new enableMobileMenu option

src/ace.tsx
Fix handling of a null or absent "markers" property.
Steps to reproduce this issue:
* Provide some markers (i.e. non-empty array) to the AceEditor component
* In a later rendering, provide instead a null or absent "markers" property
Expected result:
* The markers disappear
Actual result:
* The markers from the previous rendering are still present.
Workaround:
* Provide explicitly an empty array as "markers" property. 
This PR ensures that absent or null markers are always treated the exact same way as an empty array.
=> Fix handling of a null or absent "markers" property
