securingsincity/react-ace

- example/example.jsx
- gulpfile.js
I noticed some mix syntax and a few errors when running gulp so I updated all files containing any JSX syntax to be .jsx. Also fixed the gulp file.
> Converted js files with JSX to jsx extentions, update gulpfile

- README.md
- src/ace.jsx
Added these props that I wanted to set on component mount - think it's ok to set them here?
> Exposed some new props

- package.json
- src/ace.jsx
Hello,
I just updated the build packages.  
I was having trouble using react-ace within a react v0.13.* app.  With the updated dependencies and builds, my errors went away.  Don't know if you'd like the update as well.  
Thank you for making the package!!
Best,
Barret
> Update build packages

- package.json
added a couple build scripts to help in development.
By adding the scripts, gulp does not need to be globally installed and will use the local gulp version
Best,
Barret
> added two scripts to help in development... doesn't require global gulp

- README.md
- src/ace.jsx
> Support customizing editor properties with editorProps

- src/ace.jsx
realised this triggers its own event separate to onChange, so doesn't work with the ```if(editor.curOp && editor.curOp.command.name``` line to detect user changes.
> add support for onPaste event

- src/ace.jsx
> tabSize support

- src/ace.jsx
Added a binding for the wrapEnabled property to select the editor wrap mode.
> New property wrapEnabled

- src/ace.jsx
Call ace editor api only on props change, it will boost performance.
> call ace editor api only on props change

- README.md
- example/.babelrc
- example/index.js
- example/package.json
- example/webpack.config.js
- package.json
- src/ace.jsx
> use es2015 and react 0.14

- README.md
- src/ace.jsx
There is an option `maxLines`, but no `minLines`, so I added it in this PR.
> Added the option `minLines`

- README.md
- src/ace.jsx
Hey! This implements https://github.com/securingsincity/react-ace/issues/90. Please let me know if it seems like a worthy feature and patch. Thank you!
> enable adding commands

- README.md
- example/index.html
- example/index.js
- package.json
- src/ace.jsx
Allows you to set any other editor options in an object, like
editorProps.
> New property SetOptions

- src/ace.jsx
I implement onScroll props.
use like this:
```
onScroll={(editor) => console.log('test')}
```
> implement onScroll props

- .gitignore
- package.json
- tests/setup.js
- tests/src/ace.spec.js
-Added Sinon, Chai, Mocha, NYC, Enzyme, React-Test-Utils and JSDom
-Added Unit test for `ace.jsx`
-Added mocha run script and coverage
> Add Unit Test - Fixes #140

- package.json
- src/ace.jsx
The blank space almost killed me.
#116
> Snippets bug fixed

- .gitignore
- README.md
- src/ace.jsx
I think that's the simplest solution.
> Add defaultValue prop

- .gitignore
- README.md
- src/ace.jsx
Font size could also be a number with a unit like "1.5rem"
> Update fontSize propType

- package.json
> Update brace to v0.9.1

- package.json
- types.d.ts
With these changes the library can be used seamlessly from Typescript.
> Added Typescript's definitions.

- types.d.ts
The typings for the functions didn't appear to work, so I have declared the functions that I can and made the rest generic so they can still be used (I would appreciate help with this if anyone knows the implementation of these functions).
Also thanks to @illbexyz for writing these definitions.
> Fixed some function types in TypeScript declaration

- src/ace.jsx
This PR add support for setting scrollMargins via react props.
> Add support for scrollMargins

- src/ace.jsx
- tests/src/ace.spec.js
This PR is to update the ref to use function instead of string
https://facebook.github.io/react/docs/refs-and-the-dom.html
> Fix ref error

- src/ace.jsx
- tests/src/ace.spec.js
- types.d.ts
> OnChange event available

- README.md
- example/index.js
- src/ace.jsx
- tests/src/ace.spec.js
- types.d.ts
> Selected text

- src/ace.jsx
- tests/src/ace.spec.js
Adds resize on width change not just height
closes #207 
Will need to be reflected on the v5 branch
> Support resize on width change

- src/ace.js
- tests/src/ace.spec.js
> RA-226- Setoptions shouldn't be overridden

- src/ace.js
- src/split.js
- tests/src/ace.spec.js
- tests/src/split.spec.js
> 229 cant unset markers

- package.json
- tests/src/split.spec.js
> chore(package): update sinon to version 3.1.0

- src/ace.js
- tests/src/ace.spec.js
> Adds event to focus and blur

- docs/Ace.md
- example/index.js
- src/ace.js
> added onValidate callback

- package-lock.json
- package.json
> 5.2.2 - fix broken build because of open collective

- package.json
https://github.com/securingsincity/react-ace/issues/279
- transfered react & react-dom from dependency to peer dependency
> removed react from dependency

- docs/FAQ.md
Added sample code in FAQs about how to get the current selected text from editor.
> Added getSelectedText in FAQs

- CHANGELOG.md
- docs/Ace.md
- docs/Split.md
- package.json
- src/ace.js
- src/editorOptions.js
- src/split.js
> Adds the On Input Event

- docs/Ace.md
- package-lock.json
- src/ace.js
This PR add the feature requested in [283](https://github.com/securingsincity/react-ace/issues/283)
Replicated the onChange function behaviour to the onBlur event
The document ace.md is also updated
#283
> Onblur value

- src/ace.js
This PR fixes the issue raised in  [#317](https://github.com/securingsincity/react-ace/issues/317)
Like mentioned in the issue the strict comparison limits dynamic editor updates which causes the app to be inconsistent.The current change replaces the strict comparison of `defaultVaue` and `undefined` , with a `NOT` check on `defaultValue`. Having this condition will make the editor to keep the contents which are passed as `value` prop instead of giving priority to `defaultValue` which can be empty most often
> Default value

- .travis.yml
- package-lock.json
- src/ace.js
- tests/src/ace.spec.js
Uses a different `setValue` that handles  resetting the undo manager initially. 
https://github.com/thlorenz/brace/blob/master/index.js#L9807
Closes #223 #339
> Handle initializing undomanager

- docs/Diff.md
Minor fix for the table markup of the Diff props.
> Fixing markup of the Diff props table.

- docs/Diff.md
- example/diff.js
- src/diff.js
This PR fixes the issue raised in #427 
`onChange` prop support is added in diff.js
> Onchange support in diff

- package.json
> chore(package): update sinon to version 5.0.5

- types.d.ts
Added in the missing style prop in the AceEditorProps.
#410
> Added in the missing style property to the typings

- .eslintrc
- package-lock.json
- package.json
> chore(package): update eslint-plugin-react to version 7.8.1

- src/diff.js
Diff component to respond to changes in the value prop.
- added a componentWillReceiveProps method
https://github.com/securingsincity/react-ace/issues/479
> Diff responds to value change

- docs/FAQ.md
A fix to the FAQ on command overrides.
The example was not working, so I read the source code and fixed the FAQ to match.
N/A
https://github.com/securingsincity/react-ace/pull/287/files#diff-2cc54b67f03cff634484c0593dd4215cR91
N/A
N/A
> Fix FAQ about overriding existing commands.

- package.json
> chore(package): update webpack to version 4.17.2

- package-lock.json
- package.json
> Greenkeeper/webpack 4.19.0

- package-lock.json
- package.json
> Greenkeeper/webpack 4.20.2

- example/diff.js
- example/index.js
- example/split.js
- package-lock.json
- package.json
- src/ace.js
- src/diff.js
- src/split.js
- tests/setup.js
- tests/src/ace.spec.js
- tests/src/split.spec.js
- webpack.config.example.js
Reverts securingsincity/react-ace#528
> Revert "Replacing `brace` with `ace-builds`."

- package-lock.json
- package.json
> Add pretty-quick for precommit

- package-lock.json
- package.json
> Greenkeeper/webpack 4.23.0

- example/diff.js
> Diff editor demo fix

- src/ace.js
Added editor to ace even onFocus as per issue #389 
Made an addition to the event handler on ace.js to also relay the editor.
Fixes #389
> Add editor to onFocus event as per issue #389

- package-lock.json
- package.json
> Greenkeeper/webpack 4.26.1

- package-lock.json
- package.json
> Greenkeeper/webpack 4.28.4

- package-lock.json
- package.json
> Greenkeeper/eslint 5.15.1

- package-lock.json
- package.json
> Greenkeeper/sinon 7.2.7

- package.json
> chore(package): update sinon to version 7.3.1

- package-lock.json
- package.json
> Greenkeeper/husky 2.1.0

- package-lock.json
- package.json
> Greenkeeper/webpack 4.32.2

- src/ace.tsx
- src/types.ts
Fix type define
- correct react component state define
- fix type error in Imark
- $blockScrolling should be number | string
> fix: correct type define

- package-lock.json
- package.json
> Greenkeeper/husky 2.7.0

- package-lock.json
- package.json
> Greenkeeper/webpack 4.35.2

- package-lock.json
- package.json
> Greenkeeper/webpack cli 3.3.5

- package-lock.json
- package.json
> Greenkeeper/webpack 4.41.0

- package-lock.json
- package.json
> Greenkeeper/eslint 6.5.1

- src/types.ts
- types.d.ts
Update types to follow https://github.com/ajaxorg/ace/wiki/Configuring-Ace
Fix #737
> fix types for print margin option

- README.md
Specify that ace-builds has to be installed in order to theme the editor.
None
None
> Specify ace-builds in install command

- package-lock.json
- package.json
> Greenkeeper/webpack dev server 3.10.3

- package-lock.json
- package.json
> Greenkeeper/eslint 6.8.0

- package-lock.json
- package.json
> Greenkeeper/webpack 4.41.6

- package-lock.json
- package.json
> Greenkeeper/sinon 8.1.0

- package-lock.json
- package.json
> Greenkeeper/jsdom 16.1.0

- package-lock.json
- package.json
> Greenkeeper/@types/mocha 7.0.1

- src/ace.tsx
updated type to minimally support https://github.com/securingsincity/react-ace/blob/master/docs/FAQ.md#how-do-i-add-a-custom-mode
> fixes IAceEditorProps.mode prop to include support for custom mode

- package-lock.json
- package.json
> Greenkeeper/sinon 9.0.1

- package-lock.json
- package.json
> Greenkeeper/@types/node 13.9.1

- package-lock.json
- package.json
> Greenkeeper/prettier 2.0.5

- package-lock.json
- package.json
> Greenkeeper/webpack 4.43.0

- package-lock.json
- package.json
> Greenkeeper/mocha 7.1.2

- src/AceEditorClass.tsx
- src/ace.tsx
- src/diff.tsx
- src/editorOptions.ts
- src/types.ts
- tests/src/ace.spec.js
Get real editor type when using onLoad and onBeforeLoad props.
Fixed onCopy and onPaste events argument.
> Use Ace.Editor types

- README.md
- docs/Migrate-v7-to-v8.md
- adds notes on how to migrate to version 8
> Add version 8 migration doc, fixes #784

- docs/Migrate-v7-to-v8.md
Updated migration guide from 7 to 8, added brace/snippets migration steps
Updated the `docs/Migrate-v7-to-v8.md` 
NA
> added brace/snippets migration steps

- src/split.tsx
Changed ISplitEditorProps style properties type.
Got ts linter error about missing style prop while using SplitEditor. Shouldn't it be optional there?
Also object type seems to be more fitting for it.
> style prop type to conditional object

- example/index.js
- package.json
- src/ace.tsx
To support modify line-height.
> Support line height
